# -*- coding: utf-8 -*-
"""settings 目录资源的内置备份。

当 settings 被误删或个别文件缺失时，config.restore_missing_settings()
会按此备份恢复，保证软件不依赖外部配置目录即可启动。
"""

DEFAULT_SETTINGS = {
    '标题_Chapter.txt': "<script language=javascript src='../js/page.js'></script>\r\n<script language=javascript src='../js/chapter.js'></script>",
    '标题_Index.txt': "<script language=javascript src='../js/page.js'></script>\r\n",
    '标题_Volume.txt': '<script language=javascript src="../js/page.js"></script>',
    '标题_Readall.txt': '<script language=javascript src="../js/page.js"></script>',
    '内容_Chapter.txt': '<script language=javascript>loadtxt(parent.txt); setCookies("index",String(parent.txt)); setCookies("title",parent.document.title);</script>',
    '内容_Index.txt': '<script language="JavaScript">\r\nvar i = 0\r\nvar end = pages.length\r\nvar MaxColspan = 4\r\n\r\nwhile(i != end)\r\n{\r\n    document.write("<tr>")\r\n    for(nCount = 1;nCount <= MaxColspan;nCount++)\r\n    {\r\n        if (i == end)\r\n        {\r\n            if(nCount == 1) break;\r\n            else document.write("<td class=\'tablebody1\' align=\'middle\' style=\'width:1%;height:30\'> </td>");\r\n        }\r\n        else\r\n        {\r\n            if (pages[i][3] != undefined)\r\n            {\r\n                if(nCount == 1)\r\n                {\r\n                    if(pages[i][3].substr(0,4) == "<img")\r\n                    {\r\n                        nCount = MaxColspan - 1;\r\n                        document.write("<td colspan=1 align=center>"+pages[i][3]+"</td><td class=\'tablebody1\' colspan=" + nCount.toString() + ">"+pages[i][1]+"</td>");\r\n                        nCount = MaxColspan + 1;\r\n                        i++;\r\n                    }\r\n                    else\r\n                    {\r\n                        document.write("<td class=\'tablebody2\' colspan=" + MaxColspan.toString() + " align=\'center\' valign=\'middle\' style=\'height:30\'>"+pages[i][3]+"\u3000[<a href=javascript:loadurl(\'volume.htm\',"+i+")>分卷阅读</a>]</td>");\r\n                        document.write("</tr><tr>");\r\n                        document.write("<td class=\'tablebody1\' valign=\'middle\' style=\'width:1%;height:30\'>");\r\n                        document.write("<a href=javascript:loadurl(\'chapter.htm\',"+i+") title=\'本章字数："+pages[i][2]+"\'>"+pages[i][1]+"</a>");\r\n                        document.write("</td>");\r\n                        i++;\r\n                    }\r\n                }\r\n                else document.write("<td class=\'tablebody1\' align=\'middle\' style=\'width:1%;height:30\'> </td>");\r\n            }\r\n            else\r\n            {\r\n                document.write("<td class=\'tablebody1\' valign=\'middle\' style=\'width:1%;height:30\'>");\r\n                document.write("<a href=javascript:loadurl(\'chapter.htm\',"+i+") title=\'本章字数："+pages[i][2]+"\'>"+pages[i][1]+"</a>");\r\n                document.write("</td>");\r\n                i++;\r\n            }\r\n        }//if pages\r\n    }//for nCount\r\n    document.write("</tr>");\r\n}//while\r\nfunction gotoNextPage()\r\n{\r\n    if (window.event.keyCode == 39 && parent.txt != undefined) loadurl("chapter.htm",parent.txt);\r\n}\r\ndocument.onkeydown = gotoNextPage;\r\n</script>\r\n',
    '内容_Volume.txt': '<script language="JavaScript">\r\nif (parent.txt == undefined)\r\n{\r\n\tparent.txt = Number(ReadCookies("index"));\r\n\tparent.document.title = ReadCookies("title");\r\n}\r\nvar i = parent.txt;\r\nvar end = pages.length;\r\ndocument.write("<tr><td class=xt align=middle colspan=4><p align=left><b>"+pages[i][3]+"</b></p></td></tr>");\r\nwhile(i != end)\r\n{\r\n\tdocument.write("<tr>");\r\n\tfor(nn = 1;nn < 5;nn++)\r\n\t{\r\n\t\tif (i == end)\r\n\t\t{\r\n\t\t\tif(nn == 1) break;\r\n\t\t\telse document.write("<td width=25% height=25>&nbsp;&nbsp;</td>");\r\n\t\t}\r\n\t\telse\r\n\t\t{\r\n\t\t\tif (pages[i][3] != undefined && i != parent.txt)\r\n\t\t\t{\r\n\t\t\t\tif ( nn == 1)\r\n\t\t\t\t{\r\n\t\t\t\t\tend = i;\r\n\t\t\t\t\tbreak;\r\n\t\t\t\t}\r\n\t\t\t\telse document.write("<td  class=xt vAlign=top width=25%>&nbsp;&nbsp;</td>");\r\n\t\t\t}\r\n\t\t\telse\r\n\t\t\t{\r\n\t\t\t\tdocument.write("<td class=xt vAlign=top width=25%><a href=#"+pages[i][0]+">"+pages[i][1]+"</a></td>");\r\n\t\t\t\ti++;\r\n\t\t\t}\r\n\t\t}//if pages\r\n\t}//for nn\r\n\tdocument.write("</tr>");\r\n}//while\r\nsetCookies("index",String(parent.txt));\r\nsetCookies("title",parent.document.title);\r\n</script>',
    '内容_Readall.txt': '<script language="JavaScript">\r\nvar i = 0;\r\nvar end = pages.length;\r\nwhile(i != end)\r\n{\r\n\tdocument.write("<tr>");\r\n\tfor(nn = 1;nn < 5;nn++)\r\n\t{\r\n\t\tif (i == end)\r\n\t\t{\r\n\t\t\tif (nn == 1) break;\r\n\t\t\telse document.write("<td width=25% height=25>&nbsp;&nbsp;</td>");\r\n\t\t}\r\n\t\telse\r\n\t\t{\r\n\t\t\tif (pages[i][3] != undefined)\r\n\t\t\t{\r\n\t\t\t\tif(nn == 1)\r\n\t\t\t\t{\r\n\t\t\t\t\tif (pages[i][3].substr(0,4) == "<img")\r\n\t\t\t\t\t{\r\n\t\t\t\t\t\tdocument.write("<td colspan=1 align=center>"+pages[i][3]+"</td><td colspan=3>"+pages[i][1]+"</td>");\r\n\t\t\t\t\t\tnn=5;\r\n\t\t\t\t\t\ti++;\r\n\t\t\t\t\t}\r\n\t\t\t\t\telse\r\n\t\t\t\t\t{\r\n\t\t\t\t\t\tdocument.write("<td colspan=4 height=32><p align=left><b>"+pages[i][3]+"</b></p></td>");\r\n\t\t\t\t\t\tdocument.write("</tr></tr>");\r\n\t\t\t\t\t\tdocument.write("<td width=25% height=25><a href=#"+pages[i][0]+">"+pages[i][1]+"</a></td>");\r\n\t\t\t\t\t\ti++;\r\n\t\t\t\t\t}\r\n\t\t\t\t}\r\n\t\t\t\telse document.write("<td width=25% height=25>&nbsp;&nbsp;</td>");\r\n\t\t\t}\r\n\t\t\telse\r\n\t\t\t{\r\n\t\t\t\tdocument.write("<td width=25% height=25><a href=#"+pages[i][0]+">"+pages[i][1]+"</a></td>");\r\n\t\t\t\ti++;\r\n\t\t\t}\r\n\t\t}//if pages\r\n\t}//for nn\r\n\tdocument.write("</tr>");\r\n}//while\r\n</script>',
    '章节_Volume.txt': '<script language=javascript>\r\nfor(i = parent.txt;i < end;i++)\r\n{\r\n\tloadtxt(i);\r\n}\r\nfunction gotoNextPage()\r\n{\r\n\tif (window.event.keyCode == 13 || window.event.keyCode == 37) document.location = "index.htm";\r\n}\r\ndocument.onkeydown = gotoNextPage;\r\n</script>',
    '章节_Readall.txt': '<script language=javascript>\r\nfor(i = 0;i < end;i++)\r\n{\r\n\tloadtxt(i);\r\n}\r\nfunction gotoNextPage()\r\n{\r\n\tif (window.event.keyCode == 13 || window.event.keyCode == 37) document.location = "index.htm";\r\n}\t\r\ndocument.onkeydown=gotoNextPage;\r\n</script>',
    '链接.txt': 'https://github.com/qqzhal',
    '上一页.txt': 'javascript:loadurl("chapter.htm",prevpage)',
    '下一页.txt': 'javascript:loadurl("chapter.htm",nextpage)',
    '目录.txt': 'javascript:loadurl("index.htm",-1)',
    '模板.txt': "<script language=javascript src='../js/mb.js'></script>",
    'star.htm': '<html><head><title>作者：{作者}</title></head>\r\n<body topmargin="0" leftmargin="0" rightmargin="0" bottommargin="0" marginwidth="0" marginheight="0" style="overflow:hidden">\r\n<iframe frameborder="0" style="width:100%;height:100%" src="{默认模板}/index.htm"></iframe>\r\n</body>\r\n</html>',
    'Chapter.js': 'var prevpage = -1;\r\nvar nextpage = -1;\r\n\r\nif (parent.txt == undefined)\r\n{\r\n\tparent.txt = Number(ReadCookies("index"));\r\n\tparent.document.title = ReadCookies("title");\r\n}\r\n\r\nindex = parent.txt;\r\n\r\nswitch(index)\r\n{\r\n\tcase 0: nextpage = 1; break;\r\n\tcase pages.length - 1: prevpage = index - 1; break;\r\n\tdefault: prevpage = index - 1; nextpage = index + 1;\r\n}\r\n\r\nfunction next(a,b,c,j)\r\n{\r\n\tvar s = "";\r\n\tif(prevpage != -1 && a != "") document.write("<A href=\'javascript:loadurl(\\"chapter.htm\\",prevpage)\'>"+a+"</A>");\r\n\tif(j > 0) for(i = 1;i <= j;i++) s = s + "&nbsp;";\r\n\tif(b != "") document.write(s+"<a href=javascript:loadurl(\\"index.htm\\")>"+b+"</A>"+s);\r\n\tif(nextpage != -1 && c != "") document.write("<A href=\'javascript:loadurl(\\"chapter.htm\\",nextpage)\'>"+c+"</A>");\r\n}\r\n\r\nfunction gotoNextPage()\r\n{\r\n\tif (window.event.keyCode ==13) document.location = "index.htm";\r\n\tif (window.event.keyCode == 37 && prevpage != -1) loadurl("chapter.htm",prevpage);\r\n\tif (window.event.keyCode == 39 && nextpage != -1) loadurl("chapter.htm",nextpage);\r\n}\r\n\r\ndocument.onkeydown=gotoNextPage;',
    'Page.js': 'var pages = new Array();\r\n{PAGE}\r\n\r\nfunction loadurl(url,num)\r\n{\r\n//alert(num);\r\n\tparent.document.title = \'作者：{作者}\';\r\n\tif (num == undefined)\r\n\t{\r\n\t\tdocument.location = url;\r\n\t} \r\n\telse\r\n\t{\r\n\t\tparent.txt = num;\r\n\t\tif (num == -1 || num >= pages.length)\r\n\t\t{\r\n\t\t\tdocument.location = "index.htm";\r\n\t\t}\r\n\t\telse\r\n\t\t{ \r\n\t\t\tdocument.location = url;\r\n\t\t}\r\n\t}\r\n}\r\n\r\nfunction loadtxt(i)\r\n{\r\n\tdocument.write(\'<script language="JavaScript" src="../txt/\'+pages[i][0]+\'.txt"></script>\');\r\n}\r\n\r\nfunction setCookies(cookieName,cookieValue, expirehours)\r\n{\r\n\tvar today = new Date();\r\n\tvar expire = new Date();\r\n\texpire.setTime(today.getTime() + 3600000 * 356 * 24);\r\n\tdocument.cookie = cookieName+\'=\'+escape(cookieValue)+\';expires=\'+expire.toGMTString();\r\n}\r\n\r\nfunction ReadCookies(cookieName)\r\n{\r\n\tvar theCookie = \'\' + document.cookie;\r\n\tvar i = theCookie.indexOf(cookieName);\r\n\tif (i == -1 || cookieName == \'\') return \'\'; \r\n\tvar j=theCookie.indexOf(\';\',i);\r\n\tif (j == -1) j = theCookie.length;\r\n\treturn unescape(theCookie.substring(i + cookieName.length + 1,j));\r\n}',
    'mb.js': "document.write('<select onChange=\\'location.href=this.options[this.selectedIndex].value\\'><option value=#>模板选择{模板项目}</select>')",
    'HHP.txt': '[OPTIONS]\r\nBinary TOC=No\r\nBinary Index=No\r\nCompiled File=..\\{文件名}.chm\r\nContents File=\r\nIndex File=\r\nDefault Window=main\r\nDefault Topic=start.htm\r\nDefault Font=\r\nFull-text search=\r\nAuto Index=Yes\r\nLanguage=\r\nTitle={标题}\r\nCreate CHI file=No\r\nCompatibility=1.1 or later\r\nFull text search stop list file=\r\nDisplay compile progress=Yes\r\nDisplay compile notes=Yes\r\n\r\n[WINDOWS]\r\nmain="{标题}",,,"start.htm","start.htm",,,,,0x2A120,222,0x1046,[0,0,1440,900],0xB0000,,,,,,0\r\n\r\n[FILES]',
    'EPJ.txt': '<?xml version = "1.0"?>\r\n\r\n<project>\r\n   <version major = "1.7" minor = "0386"/>\r\n   <config>\r\n      <ebook_features basic = "true"/>\r\n      <guid>{71012DD2-9349-409D-808B-FC5C2E754E1C}</guid>\r\n      <title>{书名}</title>\r\n      <description/>\r\n      <author>{作者}</author>\r\n      <homepage/>\r\n      <email/>\r\n      <copyright>{版权}</copyright>\r\n      <comments>\r\n            <![CDATA[]]>\r\n      </comments>\r\n      <target_directory>{输出目录}</target_directory>\r\n      <ebk_filename>{输出文件}</ebk_filename>\r\n      <self_executable>yes</self_executable>\r\n      <compress_option>better ratio</compress_option>\r\n      <ebook_directory>{目录}</ebook_directory>\r\n      <start_page>{首页}</start_page>\r\n      <embeded_fonts>todo</embeded_fonts>\r\n      <customize_ebook_icon>yes</customize_ebook_icon>\r\n      <ebook_icon>{目录}\\book.ico</ebook_icon>\r\n      <enable_toc show_at_startup = "no">no</enable_toc>\r\n      <show_ebk_source_tree>yes</show_ebk_source_tree>\r\n      <show_splash delay_time = "2">no</show_splash>\r\n      <splash_image/>\r\n      <customized_logo>yes</customized_logo>\r\n      <logo_image>{目录}\\logo.gif</logo_image>\r\n      <logo_url>https://github.com/qqzhal</logo_url>\r\n      <logo_tooltip>{版权}</logo_tooltip>\r\n      <window_size cx = "" cy = "">maximize</window_size>\r\n      <window_pos left = "" top = "">screen_center</window_pos>\r\n      <border_style>sizeable</border_style>\r\n      <border_icon close = "true" minimize = "true" maximize = "true"/>\r\n      <ebook_bars toolbar = "yes" menubar = "no" searchbar = "no" statusbar = "no"/>\r\n      <about_dialog sys = "true"/>\r\n      <register_alert_dialog enable = "false" auto_popup = "false" sys = "true"/>\r\n      <security_mode encrypt_whole_book = "no" enable_wrong_pwd_url = "no" wrong_pwd_url = "">none</security_mode>\r\n      <ebook_browser_security enable_copy = "true" enable_context_menu = "true"/>\r\n      <password_expiration_settings enabled = "false" mode = "1" data = ""/>\r\n      <expiration_settings enabled = "false" mode = "0" data = "30" BeforeExpireURL = "" AfterExpireURL = "" BeforeExpireOption = "0" AfterExpireOption = "1">\r\n         <BeforeExpireMessage>\r\n               <![CDATA[]]>\r\n         </BeforeExpireMessage>\r\n         <AfterExpireMessage>\r\n               <![CDATA[]]>\r\n         </AfterExpireMessage>\r\n      </expiration_settings>\r\n      <expiration_dialog caption = "" regbtn_caption = "" regbtn_regurl = ""/>\r\n      <toolbar_button_options back = "0" forward = "0" stop = "2" refresh = "2" home = "0" print = "2" textsize = "2" fullscreen = "0" contents = "2" bookmarks = "0" exit = "0"/>\r\n   </config>\r\n   <toc/>\r\n</project>',
    'TXT模板.txt': 'document.write(" <p align=center style=\'FONT-SIZE:13.5pt;font-family:宋体\'><b><a name=\'{卷章序}\'>{卷名} {章名} </b><p>");\r\n\r\n',
    '版权.txt': '',
    '制作.txt': 'qqzhal',
}
